apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        volumeMounts:
        - name: private-jenkins-pv
          mountPath: /var/jenkins_home
      volumes:
      - name: private-jenkins-pv
        persistentVolumeClaim:
          claimName: private-jenkins-pvc
