apiVersion: v1
kind: PersistentVolume
metadata:
  name: private-mariadb-pv
  labels:
    type: mariadb
spec:
  storageClassName: mariadb
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/lib/mariadb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: private-mariadb-pvc
spec:
  storageClassName: mariadb
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: 8Gi