apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels: 
    name: mysql
spec:
  type: NodePort
  ports:
    - port: 3306
  selector:
    name: mysql
    tier: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: private-mariadb
spec:
  selector:
    matchLabels:
      name: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: mysql
        tier: mysql
    spec:
      containers:
      - image: mysql:latest
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass-59td85b2kt
              key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-pv
          mountPath: var/lib/mysql
        - name: config
          mountPath: etc/mysql
          readOnly: true
      volumes:
      - name: mysql-pv
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: config
        configMap:
          name: mysql-config
